### PR TITLE
h1 alignment on Home.js

### PR DESCRIPTION
**Pull request by tomlebeau3423**
blockcode h1 alignment in Home.js

### CODE REVIEW

**Comment by amy-corson** [comment]
Hello! We discussed this on our 5/9 team call and the consensus at this time is that we do prefer the left alignment for all major headers, but thank you for your time and work. We would love to encourage you to continue contributing in the future! Please feel free to reach out with any questions.

**Comment by tomlebeau3423** [comment]
That's understandable, But you did have an issue listed regarding the
alignment of that heading? When I looked at issue #47 I thought you were
talking about the heading. Do you mean the whole block of text with that
issue?

**Comment by tomlebeau3423** [comment]
Sorry for the misunderstanding. I've been meaning to attend a meeting, but
I get home fairly late.

**Comment by tomlebeau3423** [comment]
Sorry for the misunderstanding, I just looked again and I think you mean
the quote from streetsblog inside the text?

**Pull request closed without merging**
