### PR TITLE
Route stats page

### PR DESCRIPTION
**Pull request by smacmullan**
Implement a route stats page to show additional info per route. Route info is determined by URL parameter. The page is accessed from the navbar or by the "More Stats!" button in the map modal. There is a search bar on the page to change which route you are looking at.

This is in a state where all functionality is present and it can be merged into dev. However, the following items should be worked on:
- Adjust the search styling so the dropdown list floats over the rest of the page
- Refactor the Search component to be more generic
- Fix the reliability stat graph so its centered

### CODE REVIEW

**Comment by smacmullan** [comment]
At some point, someone should further refactor the Search component and figure out how to make the route-title use sticky position.

**Comment by KyleDolezal** [comment]
When I hover over routes, they stay white indefinitely, whereas in main branch, they only stay white when I have the mouse over them.

**Comment by KyleDolezal** [comment]
In reviewing the PR, I:
- Reviewed code changes
- Tested the functionality
- Identified an issue [here](https://github.com/chihacknight/ghost-buses-frontend/pull/65#issuecomment-1588490272)
- Rebased with `main`
- Reverted the commit that caused the issue after determining that the commit was a refactor that could safely be reverted without negatively impacting any functionality
- Approved the PR.

**Review by KyleDolezal — APPROVED** [review]
I have manually tested new and existing functionality before approving the PR. I recommend automated tests to give us confidence that future additions/refactors do not break functionality.

**Comment by KyleDolezal** [comment]
There are future opportunities for improvement, including refactoring duplicated code in modal.js and Routestats.js.

**Pull request merged**
